version: "3.9"

services:
  mywebapp:
    image: username/mywebapp:latest
    ports:
      - "8080:80"
    environment:
      - DEVOPS=Sandbox 2021
    deploy:
      replicas: 5
      networks:
      - front-tier
      - back-tier


  myjavaapp:
    image: openjdk:latest

  mydatabase:
    image: mysql:latest
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
      networks:
      - back-tier
    depends_on:
      - myjavaapp
      
 volumes:
  db-data:

networks:
  front-tier:
  back-tier:
